//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownSim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameData
    {
        public int Id { get; set; }
        public int Day { get; set; }
        public int Actions { get; set; }
        public int Villagers { get; set; }
        public int Houses { get; set; }
        public int Wells { get; set; }
        public int Farm { get; set; }
        public int Food { get; set; }
        public int Water { get; set; }
        public int Wood { get; set; }
        public int Stone { get; set; }
    }
}
