//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownSim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public int Id { get; set; }
        public Nullable<int> Food { get; set; }
        public Nullable<int> Water { get; set; }
        public Nullable<int> Wood { get; set; }
        public Nullable<int> Stone { get; set; }
    }
}
